CNPMNC/BookStore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Models;
using PagedList;
using PagedList.Mvc;

namespace BookStore.Controllers
{
    public class BookStoreController : Controller
    {
        dbQLBansachDataContext data = new dbQLBansachDataContext();

        public ActionResult SPTheochude(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }

        public ActionResult SpTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }

        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }

        private List<SACH> Laysachmoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }

        // GET: BookStore
        //public ActionResult Index(int? page)
        //{
        //    int pageSize = 5;
        //    int pageNum = (page ?? 1);
        //    var sachmoi = Laysachmoi(15);
        //    return View(sachmoi.ToPagedList(pageNum, pageSize));


        //    //var sachmoi = Laysachmoi(5);
        //    //return View(sachmoi);
        //}

        public ActionResult Index(int? page, string searchString)
        {
            var sp = from e in data.SACHes select e;
            if (!String.IsNullOrEmpty(searchString))
            {
                sp = sp.Where(s => s.Tensach.Contains(searchString));
            }
            ViewBag.SeachString = searchString;
            //tạo bien so trang
            int pageNumber = (page ?? 1);
            //tao bien quy dinh so san pham tren moi trang
            int pageSize = 6;
            return View(sp.ToList().OrderBy(n => n.Masach).ToPagedList(pageNumber, pageSize));
            //return View(db.SAN_PHAMs.ToList());
        }


        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }

        public ActionResult Nhaxuatban()
        {
            var nxb = from cd in data.NHAXUATBANs select cd;
            return PartialView(nxb);
        }

    }
}

CNPMNC/BookStore/Views/BookStore/Chude.cshtml
@model IEnumerable<BookStore.Models.CHUDE>
<p class="lead"> CHỦ ĐỀ SÁCH</p>
<div class="list-group">
    @foreach(var item in Model)
    {
        <a href="@Url.Action("SPTheochude", "BookStore",new { id = item.MaCD })" class="list-group-item">
            @item.TenChuDe
        </a>
    }
</div>

CNPMNC/BookStore/Views/BookStore/Details.cshtml
<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: red;
        }
</style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2> Thong Tin Chi Tiet Sachn </h2>
<h3> Ten sach: @Model.Tensach</h3>
<div>
    <div style="width:40%; float: left;border-left:dotted 1px;border-color:azure">
        <img src="~/images/@Model.Hinhminhhoa" width="100%" />
    </div>
    <div style="width:60%;float:left;padding:10px">
        <h4 style="font-weight:bold;color:red">Ten sach:@Model.Tensach</h4>
        <p style="text-align:justify"><span style="font-weight:bold">Mo ta:</span>@Model.Mota</p>
        <p style="text-align:justify"><span style="color:red;font-size:16pt"></span>@Model.Dongia VND</p>
    </div>
    <div>
        <div id="Datmua">
            <a href="@Url.Action("ThemGiohang","GioHang",new {@iMasach=Model.Masach,@strURL=Request.Url.ToString() }) ">
                Dat Mua
            </a>
        </div>
    </div>
</div>

CNPMNC/BookStore/Views/BookStore/Index.cshtml
@using BookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h1> ĐẶNG PHẠM PHÚ DUY - 15DH110148 - Ca3</h1>
<div class="row" style="align-content:center">
@foreach (var sach in Model)
{
    <div class="col-lg-3 col-lg-3 col-lg-3">
        <div class="thumbnail">
            <a href="@Url.Action("Details", "BookStore",new { id = sach.Masach })">
                <img alt="@sach.Tensach" src="~/images/@sach.Hinhminhhoa" width="140" height="140" />
                <div>
                    <br />
                    <h4 style="text-align:center">
                        @sach.Tensach
                    </h4>
                    <p></p>
                </div>
                <div class="ratings">
                    <p class="pull-right">15 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </a>
        </div>
    </div>


}
</div>
<footer>
    <div class="bottom">
        Trang@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
    </div>
</footer>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

CNPMNC/BookStore/Views/BookStore/Nhaxuatban.cshtml
@model IEnumerable<BookStore.Models.NHAXUATBAN>
<p class="lead"> NHÀ XUẤT BẢN</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoNXB", "BookStore",new { id = item.MaNXB })" class="list-group-item">
            @item.TenNXB
        </a>
    }
</div>

CNPMNC/BookStore/Views/BookStore/SPTheochude.cshtml
@{
    ViewBag.Title = "SPTheochude";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3>Sach theo chu De</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "BookStore",new { id = sach.Masach })">
                    <img alt="@sach.Tensach" src="~/images/@sach.Hinhminhhoa" width="200" height="200" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>

    }

</div>

CNPMNC/BookStore/Views/BookStore/SpTheoNXB.cshtml
@{
    ViewBag.Title = "SpTheoNXB";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>San pham theo NXB</h2>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "BookStore",new { id = sach.Masach })">
                    <img alt="@sach.Tensach" src="~/images/@sach.Hinhminhhoa" width="200" height="200" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>

    }

</div>
</div>